import os
import shutil
import click

# an object used to send config data to every command
class Config(object):
     def __init__(self):
         self.location = False
pass_config = click.make_pass_decorator(Config, ensure=True)

# Creating a click group
@click.group()
@click.option('--location',
              envvar='HYLLA_LOCATION',
              prompt='Specify a location to store your projects (or set HYLLA_LOCATION)',
              type=click.Path(exists=True, file_okay=False))
@pass_config
def cli(config, location):
    """Hylla. Organize all your projects from the command-line"""
    config.location = location

# 'Docs' command, used to open the docs/github in a browser window
@cli.command('docs')
def open_docs():
    """Open the documentation in your browser"""
    click.echo('https://www.github.com/adelhult/hylla')
    click.launch("https://www.github.com/adelhult/hylla")

# 'New' command:
@cli.command('new')
@click.argument('name')
@click.argument('tags', nargs=-1)
@click.option('--readme-template',
             envvar='HYLLA_README_TEMPLATE',
             type=click.Path(exists=True, dir_okay=False))
@pass_config
def new(config, name, tags, readme_template):
    """Create a new project"""

    # define vars project_name and project_dir
    project_name = name.strip().lower().replace(' ', '_')
    project_dir = os.path.join(config.location, project_name)

    # print info
    click.secho(f'The project {project_name} was created!', bg='green', fg='white')
    click.echo(f'Project name: {project_name}')
    click.echo(f'Tags: {tags}')

    # check if the folder exists
    if not os.path.exists(project_dir):
        os.mkdir(project_dir)
        click.echo('Created project dir')
    else:
        click.echo('Project dir already exists')
        click.echo('Closing program!')
        # should do more stuff here!
        exit()

    # Create a readme file in the folder
    create_readme(readme_template, project_dir, project_name)

# Function used to create the readme file
def create_readme(template_path, project_dir, project_name):
    file_path = os.path.join(project_dir, 'README.md')
    if not os.path.isfile(file_path):
        if template_path:
            # Makes a copy of the template file
            shutil.copyfile(template_path, file_path)
            click.echo('Created a README file based on the provided template')
        else:
            # No template file was provided, use the standard
            with open(file_path, 'w') as f:
                f.write(f'# {project_name}\n\n## TODO\n\n## Hylla\nThis file was generated by [Hylla](https://github.com/adelhult/hylla). If you wish to use a template of your own. Specifiy the environmental varible HYLLA_README_TEMPLATE.')
            click.echo('Created a standard README file')
    else:
        click.echo('The README does already exist')


@cli.command('list')
def list():
    """List your projects"""
    click.secho('Hello World!', fg='green')
    click.secho('Some more text', bg='blue', fg='white')
    #message = click.edit()

if __name__ == '__main__':
    cli()
